INSERT INTO USERS(USER_NAME, LOGIN, EMAIL, BIRTHDAY) VALUES ( 'Evgen', 'evgen', 'mail@mail.ru', '1988-01-14');
INSERT INTO USERS(USER_NAME, LOGIN, EMAIL, BIRTHDAY) VALUES ( 'Olga', 'olga', 'olgamail@mail.ru', '1988-10-01');
INSERT INTO USERS(USER_NAME, LOGIN, EMAIL, BIRTHDAY) VALUES ( 'Ivan', 'ivan', 'ivanmail@mail.ru', '1990-10-01');

INSERT INTO FILMS(FILM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID)
    VALUES ( 'Film1', 'film description', '1985-01-01', 120, 1);
INSERT INTO FILMS(FILM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID)
    VALUES ( 'Film2', 'film2 description', '1990-01-01', 125, 2);
INSERT INTO FILMS(FILM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID)
    VALUES ( 'Film3', 'film3 description', '1995-01-01', 130, 3);
