INSERT INTO MPA (MPA_NAME) values ('G');
INSERT INTO MPA (MPA_NAME) values ('PG');
INSERT INTO MPA (MPA_NAME) values ('PG-13');
INSERT INTO MPA (MPA_NAME) values ('R');
INSERT INTO MPA (MPA_NAME) values ('NC-17');

INSERT INTO GENRES(GENRE_NAME) values ( 'Комедия' );
INSERT INTO GENRES(GENRE_NAME) values ( 'Драма' );